const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');
const root=path.resolve(__dirname,'..'),ctx=vm.createContext({console});
for(const name of ['Presentationquality.gs','Evidencequality.gs','Articlequality.gs','MailService.gs'])vm.runInContext(fs.readFileSync(path.join(root,'apps-script',name),'utf8'),ctx);
assert.equal(ctx.publicNarrative_('成本1400（原文作14），歷經除息45元，目前續抱。',{name:'祥碩',code:'5269'}),'成本1400，歷經除息45元，目前續抱。');
assert.equal(ctx.publicNarrative_('川服(川湖)今天大跌600元。',{name:'川湖',code:'2059'}),'川湖今天大跌600元。');
assert.equal(ctx.publicNarrative_('信化身為股王。',{name:'信驊',code:'5274'}),'信驊身為股王。');
assert.equal(ctx.publicNarrative_('川服(川湖)今天大跌600元。'),'川湖今天大跌600元。');
assert.equal(ctx.displayPrice_('600','','川湖今天大跌600元'),'未說明');
assert.equal(ctx.displayPrice_('17880','','股價17880元，今天跌820元'),'17880');
const s={market:[{kind:'event',text:'量縮震盪，市場靜待CPI公布再決定方向。',headline:'量縮震盪，市場靜待CPI公布再決定方向',_evidence_verified:true}],
  watch_avoid:[{name:'川湖',code:'2059',price:'600',reason:'川服(川湖)今天大跌600元。'}]};
assert.equal(ctx.articleTitle_(s),'量縮震盪，市場靜待CPI公布再決定方向！');
const article=ctx.enforceArticleRecords_('',s,'2026/09/11');
assert(article.startsWith('文章標題：量縮震盪，市場靜待CPI公布再決定方向！'));
const html=ctx.mdToHtml_(article);
assert(/<td[^>]*white-space:nowrap[^>]*>未說明<\/td>/.test(html));
assert(!html.includes('川服'));assert(!html.includes('原文作'));
const frontend=fs.readFileSync(path.join(root,'apps-script/JavaScript.html'),'utf8');
vm.runInContext(frontend.slice(frontend.indexOf('function displayPrice_'),frontend.indexOf('// BEGIN PUBLIC NARRATIVE')),ctx);
assert.equal(ctx.displayPrice_('600','','川湖今天大跌600元'),'未說明');
console.log('PASS: v12 typo annotations, amount versus price, headline, canonical mail and unbroken missing-price label.');
