const fs=require('fs'),vm=require('vm'),assert=require('assert'),path=require('path');
const root=path.resolve(__dirname,'..'),ctx=vm.createContext({console});
const helper=fs.readFileSync(path.join(root,'apps-script/Presentationquality.gs'),'utf8');
vm.runInContext(helper,ctx);
const row={name:'宇瞻',code:'8271'};
assert.equal(ctx.publicNarrative_('講者以雨沾2379為例，張正表示正在整理。',row),'以宇瞻（8271）為例，表示正在整理。');
assert.equal(ctx.publicNarrative_('講者表示會員還有宏準。',{name:'鴻準',code:'2354'}),'表示會員還有鴻準。');
assert(ctx.publicNarrative_('嘉澤1580以下买進。',{name:'嘉澤',code:'3533'}).includes('1580以下'));
assert(ctx.publicNarrative_('嘉澤1580元附近。',{name:'嘉澤',code:'3533'}).includes('1580元'));
assert.equal(ctx.publicNarrative_('回顧外資過往操作呈現先買再賣；外資操作呈現先買再賣。').match(/先買再賣/g).length,1);
vm.runInContext(fs.readFileSync(path.join(root,'apps-script/Evidencequality.gs'),'utf8'),ctx);
vm.runInContext(fs.readFileSync(path.join(root,'apps-script/MailService.gs'),'utf8'),ctx);
const sig={holdings:[{name:'鴻準',code:'2354',note:'講者說還有宏準。'}],watch_avoid:[{...row,price:'未說明',reason:'張正以雨沾2379為例。'}]};
const source=JSON.stringify(sig),chapter=ctx.recordChapter_(sig,'2026/09/10'),html=ctx.mdToHtml_(chapter);
assert(chapter.includes('會員目前持有股票'));assert(!chapter.includes('講者說'));assert(!chapter.includes('張正'));
assert(chapter.includes('宇瞻（8271）'));assert.equal(JSON.stringify(sig),source);
assert(html.includes('<th'));assert(html.includes('<td'));assert(!html.includes('<script'));
const frontend=fs.readFileSync(path.join(root,'apps-script/JavaScript.html'),'utf8');
const block=s=>s.slice(s.indexOf('// BEGIN PUBLIC NARRATIVE V10'),s.indexOf('// END PUBLIC NARRATIVE V10'));
assert.equal(block(frontend),block(helper));
for(const field of ['r.reason,r','r.note,r','x.reason,x'])assert(frontend.includes('publicNarrative_('+field+')'));
console.log('PASS: v10 public subjects, canonical names/codes, price units, deduplication, holdings/mail tables, evidence preservation and frontend parity.');
